# Generated by Django 5.0.7 on 2024-10-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('post_date', models.DateField()),
                ('source', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('regist_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
